"use client";
import { AccountSelector } from "@/components/account-selector";
import { addFinanceAccount } from "@/lib/finance-accounts";
import { paymentMethods } from "@/lib/expense-details";
import { PlanningCalendar } from "@/components/planning-calendar";
import { moveEnvelopeGoal } from "@/lib/move-envelope-goal";
import { interfaceSizes } from "@/lib/interface-size";
import { isoWeek } from "@/lib/iso-week";
import { SettingsGroups } from "@/components/settings-groups";

import { useEffect, useMemo, useState } from "react";
import DarkModeOutlined from "@mui/icons-material/DarkModeOutlined";
import LightModeOutlined from "@mui/icons-material/LightModeOutlined";
import VisibilityOutlined from "@mui/icons-material/VisibilityOutlined";
import VisibilityOffOutlined from "@mui/icons-material/VisibilityOffOutlined";
import { EnvelopeCollection } from "@/components/envelope-collection";
import { EnvelopeViewPreferences } from "@/components/envelope-view-preferences";
import { EnvelopeActionDialog } from "@/components/envelope-action-dialog";
import { FeedbackDialog } from "@/components/feedback-dialog";
import { EnvelopeEditor } from "@/components/envelope-editor";
import { EnvelopeGoalEditor } from "@/components/envelope-goal-editor";
import { IncomeTraceDialog } from "@/components/income-trace-dialog";
import { EnvelopePlanningMenu, EnvelopePlanningDetail } from "@/components/envelope-planning";
import { ProximityControls, GlobalPlanningDialog } from "@/components/proximity-filter";
import { FinanceResetDialog } from "@/components/finance-reset-dialog";
import { resetFinanceData } from "@/lib/finance-reset";
import { EnvelopeProductsDialog, PurchaseProductsEditor, parseProductDrafts, type ProductDraft } from "@/components/finance-products";
import { saveTrackedProduct, type TrackedProduct } from "@/lib/finance-products";
import { FinanceReport } from "@/components/finance-report";
import { HistoryDateFilters } from "@/components/history-filters";
import { filterHistory } from "@/lib/finance-history";
import { ScheduledAmountEditor } from "@/components/scheduled-amount-editor";
import { saveScheduledAmount, payScheduledAmount, moveScheduledAmount, type ProximityFilter, type EnvelopePlanning, type ScheduledAmount, type PlanningItem } from "@/lib/envelope-planning";
import { PostponeEditor } from "@/components/postpone-editor";
import { useAppNavigation } from "@/components/use-app-navigation";
import { FinanceNotifications, NotificationSettings } from "@/components/finance-notifications";
import { normalizeNotificationState, type NotificationState, type NotificationUpdate, type NotificationDestination } from "@/lib/finance-notifications";
import { nextEnvelopeGrid, normalizeEnvelopeView, reorderEnvelopes, type EnvelopeView } from "@/lib/envelope-view";
import { applyEnvelopeOperation, type EnvelopeAction } from "@/lib/envelope-operation";
import type { GoalSettings } from "@/lib/envelope-goals";
import { useThemeMode, themeClass, themeNames, type ColorMode } from "@/components/theme-provider";
import { BrandLogo } from "@/components/brand-logo";
import { SectionPin } from "@/components/section-pin";
import { EnvelopeContextMenu } from "@/components/envelope-context-menu";
import { FinanceDialog } from "@/components/finance-dialog";
import { useFinanceStore } from "@/components/use-finance-store";
import { saveEnvelopeSettings, saveGoalSettings } from "@/lib/envelope-settings";
import { confirmRecurringContribution, postponeRecurringContribution, isRecurrenceDue, type Recurrence } from "@/lib/finance-recurrence";
import { createClient as createSupabaseClient, isSupabaseConfigured } from "@/lib/supabase/client";
import { archiveLedgerEnvelope, setAccountActive, migrateLegacyBank, migrateEnvelopeReferences, postMovement, repay, totals, type Account, type Ledger, type Loan, type LedgerMovement } from "@/lib/finance-ledger";

type Envelope = GoalSettings & EnvelopePlanning & { products?:TrackedProduct[]; id: string; name: string; icon: string; balance: number; color: string; archived?: boolean; goal?: number; recurrence?: Recurrence };
type Movement = LedgerMovement;
type Data = EnvelopeView & { showProximity?: boolean; summaryPrivacy: {accounts:boolean;assigned:boolean;unassigned:boolean}; notifications:NotificationState; envelopes: Envelope[]; accounts:Account[];loans:Loan[];bank: number; movements: Movement[]; hidden: boolean; fields: string[]; customNames: boolean; summaryExpanded: boolean; summaryPinned: boolean; envelopesExpanded: boolean; envelopesPinned: boolean; envelopesViewMode: "list" | "grid"; activityExpanded: boolean; activityPinned: boolean };
const initial: Data = { summaryPrivacy:{accounts:false,assigned:false,unassigned:false},notifications:normalizeNotificationState(),envelopesGridColumns:2, envelopes: [{ id:"home",name:"Hogar",icon:"🏠",balance:0,color:"peach" },{ id:"food",name:"Alimentación",icon:"🛒",balance:0,color:"green" },{ id:"transport",name:"Transporte",icon:"🚙",balance:0,color:"blue" },{ id:"savings",name:"Ahorro",icon:"🐷",balance:0,color:"amber" },{ id:"emergency",name:"Emergencia",icon:"🛡️",balance:0,color:"lilac" }],accounts:[{id:"main",name:"Cuenta corriente",type:"Banco",balance:0,active:true}],loans:[],bank:0, movements:[], hidden:false, fields:["Fecha","Monto"], customNames:false, summaryExpanded:false, summaryPinned:false, envelopesExpanded:false, envelopesPinned:false, envelopesViewMode:"list", activityExpanded:false, activityPinned:false };
const money = (n:number) => `₡${Math.round(n).toLocaleString("es-CR")}`;
const today = () => { const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"America/Costa_Rica",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date()); const v=Object.fromEntries(parts.map(p=>[p.type,p.value])); return `${v.year}-${v.month}-${v.day}T${v.hour}:${v.minute}`; };
const buildTimestamp = Date.parse(process.env.NEXT_PUBLIC_BUILD_DATE || "") || Date.now();
const hydrateData=(value:Partial<Data>):Data=>{const d={...initial,...value};const migrated=migrateLegacyBank(d.bank,d.movements,value.accounts);return {...d,...normalizeEnvelopeView(value),summaryPrivacy:{...initial.summaryPrivacy,...value.summaryPrivacy},notifications:normalizeNotificationState(value.notifications),accounts:migrated.accounts,loans:d.loans||[],bank:migrated.accounts.filter(a=>a.active).reduce((sum,a)=>sum+a.balance,0),movements:migrateEnvelopeReferences(migrated.movements,d.envelopes,d.loans||[]).sort((a,b)=>b.date.localeCompare(a.date)),summaryExpanded:d.summaryPinned,envelopesExpanded:d.envelopesPinned,activityExpanded:d.activityPinned};};

function timeSinceBuild(now:number) {
  const elapsed = Math.max(0, now - buildTimestamp);
  const units = [
    { label: "año", plural: "años", ms: 31_536_000_000 },
    { label: "mes", plural: "meses", ms: 2_592_000_000 },
    { label: "semana", plural: "semanas", ms: 604_800_000 },
    { label: "día", plural: "días", ms: 86_400_000 },
    { label: "hora", plural: "horas", ms: 3_600_000 },
    { label: "minuto", plural: "minutos", ms: 60_000 },
  ];
  const unit = units.find((item) => elapsed >= item.ms);
  if (!unit) return "hace unos segundos";
  const count = Math.floor(elapsed / unit.ms);
  return `hace ${count} ${count === 1 ? unit.label : unit.plural}`;
}

export default function HomePage() {
  const cloudEnabled=isSupabaseConfigured();
  const supabase=useMemo(()=>cloudEnabled?createSupabaseClient():null,[cloudEnabled]);
  const store=useFinanceStore<Data>(supabase,initial,hydrateData);
  return <FinanceWorkspace key={store.user?.id ?? (cloudEnabled?"guest":"local")} store={store} supabase={supabase}/>;
}

function FinanceWorkspace({store,supabase}:{store:ReturnType<typeof useFinanceStore<Data>>;supabase:ReturnType<typeof createSupabaseClient>|null}) {
  const cloudEnabled=Boolean(supabase);
  const {data,setData,ready:cloudReady,user:authUser,authLoading,status:syncStatus}=store;
  const navigation=useAppNavigation(authUser?.id||"local");
  const {view,flow,step}=navigation;
  const setView=(value:string)=>navigation.open({view:value,flow:null,overlay:null,step:0,movementEnvelopeId:null,movementId:null,reminderEnvelopeId:null});
  const setFlow=(value:"Ingreso"|"Gasto"|null)=>value?navigation.open({flow:value,step:0,overlay:null}):navigation.close();
  const setStep=(value:number)=>value<step?navigation.back():navigation.open({step:value});
  const [draft,setDraft]=useState({id:"",name:"",amount:"",date:today(),reference:"",description:"",merchant:"",paymentMethod:"",tags:"",category:"Alimentación",accountId:"main",allocations:{} as Record<string,string>,products:"",productAmount:"",unassigned:false});
  const [purchaseProducts,setPurchaseProducts]=useState<ProductDraft[]>([]);
  const movementEnvelope=navigation.movementEnvelopeId||null,movementId=navigation.movementId||null,reminderEnvelope=navigation.reminderEnvelopeId||null;
  const setMovementEnvelope=(id:string|null)=>navigation.open({movementEnvelopeId:id},true);
  const setMovementId=(id:string|null)=>navigation.open({movementId:id},true);
  const [filter,setFilter]=useState("Todos"),[search,setSearch]=useState(""),[notice,setNotice]=useState(""),[formError,setFormError]=useState("");
  const {mode,setMode,toggleMode,size,cycleSize}=useThemeMode();
  const [clock,setClock]=useState(buildTimestamp),[envelopeMenu,setEnvelopeMenu]=useState<{id:string;anchor:HTMLElement}|null>(null);
  const envelopeDraft=(["envelope","goal","postpone"].includes(navigation.overlay||"")?navigation.context:null) as (Envelope & {returnToPlanning?:boolean})|null;
  const repayLoan=(navigation.overlay==="repay"?navigation.context:null) as (Loan&{operationId:string})|null;
  const envelopeAction=(navigation.overlay==="action"?navigation.context:null) as {kind:EnvelopeAction;sourceId:string;id:string}|null;
  const [summaryMenu,setSummaryMenu]=useState<{key:"accounts"|"assigned"|"unassigned";label:string;anchor:HTMLElement}|null>(null);
  const showAccountForm=navigation.overlay==="account",showEnvelopeForm=navigation.overlay==="envelope";
  const setShowAccountForm=(open:boolean)=>{setFormError("");if(open)navigation.open({overlay:"account",context:null});else navigation.close();};
  const openEditor=(envelope:Envelope|null)=>{setFormError("");navigation.open({overlay:"envelope",context:envelope});};
  const setRepayLoan=(loan:Loan|null)=>{setFormError("");if(loan)navigation.open({overlay:"repay",context:{...loan,operationId:crypto.randomUUID()}});else navigation.close();};
  const setEnvelopeAction=(action:{kind:EnvelopeAction;sourceId:string}|null)=>{setFormError("");if(action)navigation.open({overlay:"action",context:{...action,id:crypto.randomUUID()}});else navigation.close();};
  const openGoal=(envelope:Envelope)=>navigation.open({overlay:"goal",context:envelope});
  const [planningAnchor,setPlanningAnchor]=useState<HTMLElement|null>(null);
  const planningContext=(["planning","planningDetail","scheduled"].includes(navigation.overlay||"")?navigation.context:null) as {envelopeId:string;filter?:ProximityFilter;kind?:PlanningItem["kind"];itemId?:string;pay?:boolean;original?:ScheduledAmount|null}|null;
  const planningEnvelope=data.envelopes.find(e=>e.id===planningContext?.envelopeId&&!e.archived);
  const openPlanning=(envelopeId:string,anchor:HTMLElement,filter?:ProximityFilter)=>{setPlanningAnchor(anchor);navigation.open({overlay:"planning",context:{envelopeId,filter}});};
  const openScheduled=(envelopeId:string,original:ScheduledAmount|null=null)=>navigation.open({overlay:"scheduled",context:{envelopeId,original}});

  const updateNotifications:NotificationUpdate=update=>setData(d=>({...d,notifications:update(d.notifications)}));
  useEffect(()=>{const timer=window.setTimeout(()=>setClock(Date.now()),0);const interval=window.setInterval(()=>setClock(Date.now()),60_000);return()=>{window.clearTimeout(timer);window.clearInterval(interval);};},[]);
  const [authBusy,setAuthBusy]=useState(false),[authEmail,setAuthEmail]=useState(""),[authPassword,setAuthPassword]=useState(""),[authError,setAuthError]=useState(""),[authMode,setAuthMode]=useState<"login"|"signup">("login");
  const submitAuth=async(e:React.FormEvent<HTMLFormElement>)=>{
    e.preventDefault();if(!supabase)return;setAuthBusy(true);setAuthError("");
    const result=authMode==="login"?await supabase.auth.signInWithPassword({email:authEmail,password:authPassword}):await supabase.auth.signUp({email:authEmail,password:authPassword});
    if(result.error)setAuthError(result.error.message);
    else if(authMode==="signup"&&!result.data.session)setAuthError("Cuenta creada. Revisa tu correo para confirmar y luego inicia sesión.");
    setAuthBusy(false);
  };
  const ledger:Ledger={accounts:data.accounts,envelopes:data.envelopes,loans:data.loans,movements:data.movements};
  const financialTotals=totals(ledger), assigned=financialTotals.assigned, available=financialTotals.unassigned;
  const commitLedger=(operation:(current:typeof ledger)=>typeof ledger)=>{try{setData(current=>{const next=operation({accounts:current.accounts,envelopes:current.envelopes,loans:current.loans,movements:current.movements});return {...current,...next,envelopes:next.envelopes as Envelope[],movements:next.movements as Movement[],bank:totals(next).accounts};});return true;}catch(error){setFormError(error instanceof Error?error.message:"No se pudo completar la operación.");setNotice(error instanceof Error?error.message:"No se pudo completar la operación.");window.setTimeout(()=>setNotice(""),3500);return false;}};
  const display=(n:number)=>data.hidden?"••••••":money(n);
  const activeEnvelopes=data.envelopes.filter(e=>!e.archived);
  const recurrenceDue=(e:Envelope)=>isRecurrenceDue(e,today().slice(0,10));
  const togglePin=(key:"summary"|"envelopes"|"activity")=>setData(d=>{const pk=`${key}Pinned` as keyof Data;return {...d,[pk]:!Boolean(d[pk])};});
  const saveEnvelope=(patch:{name:string;icon:string})=>{const original=envelopeDraft;const requested:Envelope=original?{...original,...patch}:{id:crypto.randomUUID(),...patch,color:"green",balance:0};setData(d=>({...d,envelopes:saveEnvelopeSettings(d.envelopes,requested,original)}));setNotice(original?"Cambios guardados en el sobre.":"Sobre creado.");};
  const archiveEnvelope=(e:Envelope)=>{if(confirm(`¿Archivar “${e.name}”? Se conservarán sus movimientos.`)&&commitLedger(current=>archiveLedgerEnvelope(current,e.id)))setNotice("Sobre archivado");};
  const confirmRecurrence=(e:Envelope)=>{if(!e.recurrence)return;const due=e.recurrence.nextDate;if(commitLedger(current=>confirmRecurringContribution(current,e.id,due,today()))){setNotice(data.hidden?"Aporte registrado.":`${money(e.recurrence.amount)} asignados correctamente a ${e.name}.`);window.setTimeout(()=>setNotice(""),2600);}};
  const postponeRecurrence=(e:Envelope)=>{navigation.open({overlay:"postpone",context:e});};
  const confirmRepayment=(loan:Loan&{operationId:string},amount:number)=>{setFormError("");if(!amount){setFormError("Debes ingresar el monto que quieres devolver.");return;}const ok=commitLedger(current=>repay(current,loan.id,amount,today(),loan.operationId));if(ok){setRepayLoan(null);setNotice(data.hidden?"Devolución registrada.":`${money(amount)} devueltos correctamente de ${loan.targetName} a ${loan.sourceName}.`);window.setTimeout(()=>setNotice(""),2400);}};
  const createAccount=(name:string,type:string)=>{const id=crypto.randomUUID();setData(d=>({...d,accounts:addFinanceAccount(d.accounts,{id,name,type})}));return id;};
  const openFlow=(type:"Ingreso"|"Gasto",envelopeId?:string)=>{setPurchaseProducts([]);navigation.open({flow:type,flowEnvelopeId:envelopeId??null,step:0,overlay:null,context:null});setFormError("");setDraft({id:crypto.randomUUID(),name:"",amount:"",date:today(),reference:"",description:"",merchant:"",paymentMethod:"",tags:"",category:"Alimentación",accountId:data.accounts.find(a=>a.active)?.id||"main",allocations:{},products:"",productAmount:"",unassigned:false});};
  const flowEnvelopeId=flow?navigation.flowEnvelopeId:null;
  const flowEnvelope=data.envelopes.find(e=>e.id===flowEnvelopeId);
  const flowAllocations=flowEnvelopeId?{[flowEnvelopeId]:draft.amount}:draft.allocations;
  const totalAlloc=Object.values(flowAllocations).reduce((s,n)=>s+(Number(n)||0),0), amount=Number(draft.amount)||0;
  const suggestedName=()=>{const parts:Record<string,string>={Fecha:new Date(draft.date).toLocaleDateString("es-CR"),Hora:new Date(draft.date).toLocaleTimeString("es-CR",{hour:"2-digit",minute:"2-digit"}),Monto:money(amount),Categoría:draft.category,"Tipo de ingreso":flow==="Ingreso"?"Ingreso":draft.category,Semana:draft.date?`Semana ${isoWeek(draft.date).week}`:"",Número:`#${String(data.movements.filter(m=>m.type===flow).length+1).padStart(3,"0")}`};return data.fields.map(k=>parts[k]).filter(Boolean).join(" - ")||money(amount);};
  const finish=()=>{if(!flow)return;setFormError("");if(!draft.date){setFormError("Selecciona la fecha y hora del movimiento.");return;}if(Object.values(flowAllocations).some(value=>value.trim()!==""&&(!Number.isSafeInteger(Number(value))||Number(value)<0))){setFormError("Los montos asignados deben ser enteros mayores o iguales a cero.");return;}const name=draft.name.trim()||suggestedName();const envelopeAllocations=draft.unassigned?[]:Object.entries(flowAllocations).filter(([,value])=>Number(value)>0).map(([id,value])=>({id,amount:Number(value)}));const products=flow==="Gasto"?parseProductDrafts(purchaseProducts):[];const ok=commitLedger(current=>postMovement(current,{id:draft.id,type:flow,amount,accountId:draft.accountId,envelopeAllocations,date:draft.date,name,category:flow==="Gasto"?draft.category:"Ingreso",description:draft.description,merchant:draft.merchant,reference:draft.reference,paymentMethod:draft.paymentMethod,tags:draft.tags.split(","),products}));if(ok){setFlow(null);setNotice(`${flow} registrado`);setTimeout(()=>setNotice(""),2400);}};
  const filtered=useMemo(()=>filterHistory(data.movements,{movementId,envelopeId:movementEnvelope,type:filter,search,from:navigation.historyFrom,to:navigation.historyTo}),[data.movements,filter,search,movementEnvelope,movementId,navigation.historyFrom,navigation.historyTo]);
  const navigate=(nextView:string,button?:HTMLButtonElement)=>{setView(nextView);window.scrollTo({top:0});setEnvelopeMenu(null);if(nextView==="Movimientos"){setMovementId(null);setMovementEnvelope(null);setSearch("");setFilter("Todos");}if(button&&window.matchMedia("(max-width:650px)").matches){const nav=button.parentElement?.parentElement;nav?.scrollTo({left:button.parentElement!.offsetLeft,behavior:"smooth"});}};
  const showEnvelopeMovements=(e:Envelope)=>{setSearch("");setFilter("Todos");navigation.open({view:"Movimientos",flow:null,overlay:null,step:0,movementId:null,movementEnvelopeId:e.id,reminderEnvelopeId:null});window.scrollTo({top:0});};
  const menuEnvelope=data.envelopes.find(e=>e.id===envelopeMenu?.id);
  const toggleField=(field:string)=>setData(d=>({...d,fields:d.fields.includes(field)?d.fields.filter(f=>f!==field):[...d.fields,field]}));
  const syncLabel:Record<string,string>={local:"Solo navegador",loading:"Cargando datos…",synced:"Datos de Supabase · copia local",syncing:"Guardando en Supabase…",error:"Sin sincronizar · revisa el aviso",conflict:"Conflicto · copia local"};
  const syncIcon:Record<string,string>={local:"◷",loading:"◌",synced:"☁",syncing:"↻",error:"⚠",conflict:"⚠"};

  const clearLocalData=()=>{if(!confirm(cloudEnabled?"¿Limpiar la copia de este navegador? Tus datos de Supabase no se modificarán.":"¿Reiniciar los datos de este navegador? Se conservará una copia de respaldo local."))return;try{store.clearLocalCopy();setNotice(cloudEnabled?"Copia local limpiada. Los datos de Supabase siguen intactos.":"Datos locales reiniciados. El respaldo anterior sigue disponible.");}catch(error){setNotice(error instanceof Error?error.message:"No se pudo limpiar la copia local.");}};
  const loadRemoteCopy=()=>{if(confirm("Se guardará un respaldo de los cambios locales pendientes y se cargarán los datos actuales de Supabase. ¿Continuar?"))void store.reloadFromCloud();};
  const openProximity=(filter?:ProximityFilter)=>navigation.open({overlay:"proximity",context:{filter}});
  const resetFinances=(keep:boolean)=>{setPurchaseProducts([]);store.replaceWithBackup(current=>resetFinanceData(current,initial,keep));if(!keep)setMode("light");setEnvelopeMenu(null);setSummaryMenu(null);setPlanningAnchor(null);setSearch("");setFilter("Todos");setFormError("");navigation.reset();setNotice("Datos financieros restablecidos. El respaldo anterior está disponible en Configuración.");};
  const renderEnvelopes=()=><EnvelopeCollection showProximity={data.showProximity!==false} envelopes={activeEnvelopes} view={data} menuId={envelopeMenu?.id} display={display} privateMode={data.hidden} today={today().slice(0,10)} onList={()=>setData(d=>({...d,envelopesViewMode:"list"}))} onGrid={()=>setData(d=>({...d,...nextEnvelopeGrid(d)}))} onMenu={(id,anchor)=>setEnvelopeMenu(envelopeMenu?.id===id?null:{id,anchor})} planningId={navigation.overlay==="planning"?planningContext?.envelopeId:undefined} onPlanning={openPlanning} onCreate={()=>openEditor(null)} onNewMovement={id=>navigation.open({overlay:"new",context:{envelopeId:id}})} onReorder={ids=>setData(d=>({...d,envelopes:reorderEnvelopes(d.envelopes,ids)}))}/>;
  const openNotification=(destination:NotificationDestination)=>{setSearch("");setFilter("Todos");navigation.open({view:destination.page,overlay:null,flow:null,step:0,movementId:destination.movementId||null,movementEnvelopeId:null,reminderEnvelopeId:destination.envelopeId||null},true);window.scrollTo({top:0});};
  if((cloudEnabled&&authLoading)||(!cloudReady&&(!cloudEnabled||authUser)))return <div className="auth-screen"><section className="auth-card"><BrandLogo />{store.error?<><h1>No se pudieron cargar tus datos</h1><p>{store.error}</p><p>Tus datos guardados se conservan. Las escrituras están pausadas.</p>{cloudEnabled&&<button className="primary wide" onClick={()=>void store.retry()}>Volver a intentar</button>}<button className="secondary wide" onClick={store.downloadBackup}>Descargar copia de respaldo</button>{authUser&&<button className="auth-switch" onClick={()=>void supabase?.auth.signOut()}>Cerrar sesión</button>}</>:<><div className="auth-spinner"/><h1>{authLoading?"Conectando con tu cuenta":"Cargando tus datos"}</h1><p>Un momento, estamos preparando tu espacio financiero.</p></>}</section></div>;
  if(cloudEnabled&&!authUser)return <div className="auth-screen"><form className="auth-card" onSubmit={submitAuth}><BrandLogo /><div className="overline">TUS FINANZAS, A TU MANERA</div><h1>{authMode==="login"?"Bienvenido de nuevo":"Crea tu cuenta"}</h1><p>{authMode==="login"?"Inicia sesión para sincronizar tus sobres y movimientos.":"Tus datos se guardarán de forma privada en tu cuenta."}</p><label htmlFor="finance-correo-electr-nico-1">Correo electrónico</label><input id="finance-correo-electr-nico-1" type="email" autoComplete="email" required value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="tu@correo.com"/><label htmlFor="finance-contrase-a-2">Contraseña</label><input id="finance-contrase-a-2" type="password" minLength={6} autoComplete={authMode==="login"?"current-password":"new-password"} required value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder="Al menos 6 caracteres"/>{(authError||store.error)&&<div className="auth-error">{authError||store.error}</div>}<button className="primary wide" disabled={authBusy}>{authBusy?"Un momento…":authMode==="login"?"Iniciar sesión":"Crear cuenta"}</button><button type="button" className="auth-switch" onClick={()=>{setAuthMode(authMode==="login"?"signup":"login");setAuthError("")}}>{authMode==="login"?"¿Primera vez? Crea una cuenta":"Ya tienes cuenta? Inicia sesión"}</button></form></div>;

  return <div className={`finance-app ${themeClass(mode)}`}>
    <aside className="side-nav" aria-label="Navegación principal"><button className="logo-link" onClick={()=>navigate("Inicio")}><BrandLogo /></button><div className="side-caption">TU DINERO</div><div className="nav-pages">{[["Inicio","Movimientos","Sobres","Cuentas"],["Préstamos","Reportes","Recordatorios","Configuración"]].map((group,groupIndex)=><div className="nav-group" key={groupIndex} aria-label={`Grupo ${groupIndex+1} de navegación`}>{group.map((v,i)=><button key={v} className={`nav-item ${view===v?"selected":""}`} aria-current={view===v?"page":undefined} onClick={event=>navigate(v,event.currentTarget)}><span aria-hidden="true">{["⌂","⇄","▣","▤","↩","▥","◷","⚙"][groupIndex*4+i]}</span><span className="nav-label">{v}</span></button>)}</div>)}</div><span className="nav-hint">Desliza · 2 grupos</span><div className="side-bottom"><div className="side-tip">✦ <strong>Un paso a la vez.</strong><br/>Tu dinero, con intención.</div><div className="user-chip"><span>M</span><div><b>{authUser?.email||"Mi espacio"}</b><small>{syncLabel[syncStatus]}</small></div>{authUser&&<button className="logout" onClick={()=>void supabase?.auth.signOut()}>Salir</button>}</div></div></aside>
    <main className="workspace"><header className="app-header"><button className="home-link" onClick={()=>navigate("Inicio")} aria-label="Ir a Inicio">Inicio</button><div className="header-tools"><button className="header-control" aria-label={`Tamaño de interfaz: ${interfaceSizes[size]}. Cambiar a ${interfaceSizes[(size+1)%3]}`} title={`Tamaño: ${interfaceSizes[size]}`} onClick={cycleSize}><span aria-hidden="true">A＋</span></button><button className="header-control" aria-label={`Cambiar tema. Actual: ${themeNames[mode]}`} title={`Tema: ${themeNames[mode]}`} onClick={toggleMode}>{mode==="dark"?<LightModeOutlined/>:<DarkModeOutlined/>}</button><button className="header-control" aria-label={data.hidden?"Mostrar montos":"Ocultar montos"} title={data.hidden?"Mostrar montos":"Privacidad: ocultar montos"} aria-pressed={data.hidden} onClick={()=>setData(d=>({...d,hidden:!d.hidden}))}>{data.hidden?<VisibilityOffOutlined/>:<VisibilityOutlined/>}</button><FinanceNotifications state={data.notifications} onChange={updateNotifications} movements={data.movements} envelopes={data.envelopes} today={today().slice(0,10)} ready={cloudReady} privateMode={data.hidden} open={navigation.overlay==="notifications"} onOpen={()=>navigation.open({overlay:"notifications"})} onClose={navigation.close} onNavigate={openNotification}/></div><span className={`sync-indicator ${syncStatus}`} role="status" title={syncLabel[syncStatus]}><i>{syncIcon[syncStatus]}</i>{syncLabel[syncStatus]}</span></header>
    <div className={`page-content ${view==="Inicio"||view==="Sobres"?"envelope-page":""}`}>{cloudEnabled&&store.error&&<section className="sync-warning" role="alert"><b>{syncStatus==="conflict"?"Hay cambios de otro dispositivo":"Tus cambios todavía no están sincronizados"}</b><p>{store.error}</p><div><button className="secondary" onClick={store.downloadBackup}>Descargar mis cambios</button><button className="secondary" onClick={()=>void store.retry()}>Volver a comprobar</button>{syncStatus==="conflict"&&<button className="primary" onClick={loadRemoteCopy}>Cargar datos de Supabase</button>}</div></section>}<div className="page-title"><div><div className="overline">✦ TU DINERO, CON INTENCIÓN</div><h1>{view==="Inicio"?"Mis Sobres":view==="Cronograma"?"Cronograma de aportes y metas":view}</h1><p>{view==="Inicio"?"Cada peso tiene un lugar. Aquí puedes ver el tuyo.":view==="Movimientos"?"Todo lo que entra y sale, en un solo lugar.":view==="Sobres"?"Organiza tu dinero para lo que más importa.":view==="Reportes"?"Tus movimientos registrados, en un solo lugar.":"Haz que la app funcione a tu manera."}</p></div><button className="primary" aria-label="Nuevo movimiento" onClick={()=>navigation.open({overlay:"new"})}>＋ <span>Nuevo movimiento</span></button></div>
    {view==="Inicio"&&<>
      <section className="section accordion-section"><div className="accordion-heading"><button className="accordion-toggle" aria-expanded={data.summaryExpanded} aria-controls="summary-content" onClick={()=>setData(d=>({...d,summaryExpanded:!d.summaryExpanded}))}><span>Resumen financiero</span><span>{data.summaryExpanded?"⌃":"›"}</span></button>{data.summaryExpanded&&<SectionPin pinned={data.summaryPinned} section="resumen financiero" onToggle={()=>togglePin("summary")}/>}</div>{data.summaryExpanded&&<div className="summary-row" id="summary-content"><Summary icon="▣" label="En cuentas" value={data.summaryPrivacy.accounts?"••••••":display(financialTotals.accounts)} onPrivacy={event=>setSummaryMenu({key:"accounts",label:"En cuentas",anchor:event.currentTarget})} foot="Saldo"/><Summary icon="◈" label="Asignado" value={data.summaryPrivacy.assigned?"••••••":display(assigned)} onPrivacy={event=>setSummaryMenu({key:"assigned",label:"Asignado",anchor:event.currentTarget})} foot="En tus sobres"/><Summary icon="✳" label="Sin asignar" value={data.summaryPrivacy.unassigned?"••••••":display(available)} onPrivacy={event=>setSummaryMenu({key:"unassigned",label:"Sin asignar",anchor:event.currentTarget})} foot="Disponible" accent/></div>}</section>
      <section className="section accordion-section"><div className="accordion-heading envelope-heading"><button className="accordion-toggle" aria-expanded={data.envelopesExpanded} aria-controls="envelopes-content" onClick={()=>setData(d=>({...d,envelopesExpanded:!d.envelopesExpanded}))}><span>Mis sobres <span className="counter">{activeEnvelopes.length}</span></span><span>{data.envelopesExpanded?"⌃":"›"}</span></button>{data.envelopesExpanded&&<SectionPin pinned={data.envelopesPinned} section="mis sobres" onToggle={()=>togglePin("envelopes")}/>}{data.showProximity!==false&&<div className="envelope-proximity"><ProximityControls onChange={openProximity}/></div>}</div>{data.envelopesExpanded&&<div id="envelopes-content">{renderEnvelopes()}</div>}</section>
      <div className="quick-actions"><div><small>NUEVO MOVIMIENTO</small><h3>¿Qué quieres registrar?</h3></div><button onClick={()=>openFlow("Ingreso")}><i>＋</i><b>Entrada</b><small>Registrar ingreso</small></button><button onClick={()=>openFlow("Gasto")}><i className="minus">−</i><b>Salida</b><small>Registrar gasto</small></button></div>
      <section className="section recent accordion-section"><div className="accordion-heading"><button className="accordion-toggle" aria-expanded={data.activityExpanded} aria-controls="activity-content" onClick={()=>setData(d=>({...d,activityExpanded:!d.activityExpanded}))}><span>Actividad reciente</span><span>{data.activityExpanded?"⌃":"›"}</span></button>{data.activityExpanded&&<SectionPin pinned={data.activityPinned} section="actividad reciente" onToggle={()=>togglePin("activity")}/>}{data.activityExpanded&&<button className="text-btn" onClick={()=>navigate("Movimientos")}>Ver historial →</button>}</div>{data.activityExpanded&&<div id="activity-content"><MovementList items={data.movements.slice(0,4)} hidden={data.hidden} onTrace={id=>navigation.open({overlay:"incomeTrace",context:{movementId:id}})}/></div>}</section>
    </>}
    {view==="Movimientos"&&<section className="section page-panel">{movementId&&<div className="context-filter"><span>Movimiento seleccionado</span><button onClick={()=>setMovementId(null)}>Ver historial completo</button></div>}{movementEnvelope&&<div className="context-filter"><span>Movimientos de <b>{data.envelopes.find(e=>e.id===movementEnvelope)?.name||"Sobre archivado"}</b></span><button aria-label="Ver todos los movimientos" onClick={()=>setMovementEnvelope(null)}>Quitar filtro ×</button></div>}<div className="toolbar"><input className="search" placeholder="⌕  Buscar por nombre o sobre…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Ingreso</option><option>Gasto</option><option>Asignación</option><option>Desasignación</option><option>Transferencia</option><option>Préstamo</option><option>Devolución</option></select></div><label htmlFor="history-envelope">Filtrar por sobre</label><select id="history-envelope" value={movementEnvelope||""} onChange={event=>{setMovementId(null);setMovementEnvelope(event.target.value||null);}}><option value="">Todos los sobres</option>{data.envelopes.map(e=><option key={e.id} value={e.id}>{e.name}{e.archived?" (archivado)":""}</option>)}</select><HistoryDateFilters from={navigation.historyFrom||""} to={navigation.historyTo||""} onChange={({from,to})=>navigation.open({historyFrom:from,historyTo:to},true)}/><MovementList items={filtered} hidden={data.hidden} onTrace={id=>navigation.open({overlay:"incomeTrace",context:{movementId:id}})}/>{movementEnvelope&&data.movements.some(m=>m.allocations.some(a=>!a.envelopeId))&&<p className="flow-intro">Algunos movimientos antiguos no identifican su sobre con certeza. Se conservan en el historial completo.</p>}</section>}
    {view==="Sobres"&&<section className="section page-panel"><div className="money-banner"><span>Dinero asignado a sobres</span><b>{display(assigned)}</b></div>{renderEnvelopes()}</section>}
    {view==="Cuentas"&&<section className="section page-panel"><div className="money-banner"><span>Total en cuentas activas</span><b>{display(financialTotals.accounts)}</b></div>{data.accounts.map(account=><div className="account-row" key={account.id}><span><b>{account.name}</b><small>{account.type} · {account.active?"Activa":"Inactiva"}</small></span><strong>{display(account.balance)}</strong>{account.balance===0&&<button className="secondary" onClick={()=>commitLedger(current=>setAccountActive(current,account.id,!account.active))}>{account.active?"Desactivar":"Activar"}</button>}</div>)}<button className="add-envelope" onClick={()=>setShowAccountForm(true)}>＋ Agregar cuenta</button></section>}
    {view==="Préstamos"&&<section className="section page-panel"><h2 className="subhead">Préstamos entre sobres</h2>{data.loans.length?data.loans.map(loan=><div className="loan-row" key={loan.id}><div><b>{loan.sourceName} → {loan.targetName}</b><small>{loan.status} · Original {display(loan.amount)} · Pendiente {display(loan.outstanding)}</small></div>{loan.outstanding>0&&<button className="primary" disabled={(data.envelopes.find(e=>e.id===loan.targetId)?.balance||0)<=0} onClick={()=>setRepayLoan(loan)}>Devolver</button>}</div>):<div className="empty-state"><span>↔</span><b>No hay préstamos registrados</b><small>Presta entre sobres desde el menú de opciones de un sobre.</small></div>}</section>}
    {view==="Recordatorios"&&<section className="section page-panel"><button className="secondary wide" onClick={()=>navigate("Cronograma")}>Cronograma de aportes y metas →</button><h2 className="subhead">Aportes pendientes</h2>{reminderEnvelope&&<div className="context-filter"><span>{data.envelopes.find(e=>e.id===reminderEnvelope)?.name}</span><button onClick={()=>navigation.open({reminderEnvelopeId:null},true)}>Ver todos los recordatorios</button></div>}<p className="flow-intro">Los aportes recurrentes nunca se realizan automáticamente.</p>{activeEnvelopes.filter(e=>(!reminderEnvelope||e.id===reminderEnvelope)&&recurrenceDue(e)).length?activeEnvelopes.filter(e=>(!reminderEnvelope||e.id===reminderEnvelope)&&recurrenceDue(e)).map(e=><div className="reminder-card" key={e.id}><div><b>{e.icon} {e.name}</b><small>{display(e.recurrence!.amount)} · {e.recurrence!.frequency} · Próximo: {new Date(`${e.recurrence!.nextDate}T12:00:00`).toLocaleDateString("es-CR",{day:"numeric",month:"short",year:"numeric",timeZone:"America/Costa_Rica"})}</small>{available<e.recurrence!.amount&&<small className="negative">Fondos insuficientes: necesitas {display(e.recurrence!.amount-available)} más.</small>}</div><div className="reminder-actions"><button className="primary" onClick={()=>confirmRecurrence(e)}>Confirmar</button><button className="secondary" onClick={()=>postponeRecurrence(e)}>Posponer</button><button className="secondary" onClick={()=>openGoal(e)}>Modificar</button></div></div>):<div className="empty-state"><span>◷</span><b>No tienes aportes pendientes</b><small>Los aportes próximos aparecerán aquí cuando llegue su fecha.</small></div>}</section>}
    {view==="Cronograma"&&<PlanningCalendar envelopes={data.envelopes} today={today().slice(0,10)} date={navigation.calendarDate||today().slice(0,10)} scale={navigation.calendarScale||"Mes"} onChange={(calendarDate,calendarScale)=>navigation.open({calendarDate,calendarScale},true)} display={display} privateMode={data.hidden} onSelect={entry=>{if(entry.item)navigation.open({overlay:"planningDetail",context:{envelopeId:entry.envelopeId,itemId:entry.item.id,kind:entry.item.kind}});else {const envelope=data.envelopes.find(e=>e.id===entry.envelopeId);if(envelope)navigation.open({overlay:"goal",context:{...envelope,returnToPlanning:true}});}}}/>}
    {view==="Reportes"&&<section className="section page-panel"><FinanceReport movements={data.movements} month={navigation.reportMonth??today().slice(0,7)} onMonth={reportMonth=>navigation.open({reportMonth},true)} display={display}/></section>}
    {view==="Configuración"&&<SettingsGroups><h2>Apariencia</h2><label htmlFor="appearance-theme">Tema de Finanzas</label><select id="appearance-theme" value={mode} onChange={event=>setMode(event.target.value as ColorMode)}>{Object.entries(themeNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><h2>Privacidad</h2><div className="setting-row"><div><b>Vista privada</b><small>Oculta los montos en la pantalla.</small></div><button className={`switch ${data.hidden?"on":""}`} onClick={()=>setData(d=>({...d,hidden:!d.hidden}))}>{data.hidden?"Sí":"No"}</button></div><h2>Vista de sobres</h2><label className="check-label"><input type="checkbox" checked={data.showProximity!==false} onChange={event=>setData(d=>({...d,showProximity:event.target.checked}))}/>Mostrar proximidad</label><EnvelopeViewPreferences value={data} onChange={value=>setData(d=>({...d,...value}))}/><h2>Notificaciones y sonidos</h2><NotificationSettings state={data.notifications} onChange={updateNotifications}/><h2>Nombres y registro</h2><div className="setting-row"><div><b>Nombre automático de ingresos</b><small>Elige qué datos forman el nombre sugerido.</small></div><button className={`switch ${!data.customNames?"on":""}`} onClick={()=>setData(d=>({...d,customNames:!d.customNames}))}>{data.customNames?"Manual":"Auto"}</button></div><div className="field-options">{["Fecha","Hora","Monto","Tipo de ingreso","Categoría","Semana","Número"].map(f=><label key={f}><input type="checkbox" checked={data.fields.includes(f)} onChange={()=>toggleField(f)}/>{f==="Semana"?"Semana del año (ISO 8601)":f}<span>⠿</span></label>)}</div><div className="setting-row"><div><b>Nombre de gastos</b><small>También puedes escribir nombres al registrar un gasto.</small></div></div><h2>Datos y respaldo</h2><p className="flow-intro">{syncLabel[syncStatus]}</p><div className="setting-row"><div><b>Copia de respaldo</b><small>Descarga tus datos y las copias pendientes conservadas en este navegador.</small></div><button className="secondary" onClick={store.downloadBackup}>Descargar</button></div><button className="danger-link" disabled={cloudEnabled&&(store.pending||syncStatus!=="synced")} onClick={clearLocalData}>{cloudEnabled?"Limpiar copia local":"Reiniciar datos locales"}</button>{cloudEnabled&&<p className="flow-intro">Limpiar la copia local no modifica saldos ni movimientos en Supabase. Primero deben estar sincronizados los cambios.</p>}<button className="danger-link" disabled={!cloudReady||(cloudEnabled&&(store.pending||syncStatus!=="synced"))} onClick={()=>navigation.open({overlay:"reset"})}>Borrar movimientos y restablecer saldos</button><h2>Comentarios</h2><button className="secondary" onClick={()=>navigation.open({overlay:"feedback"})}>Enviar sugerencia</button></SettingsGroups>}
    <footer className="footer"><span>Con calma, un día a la vez ♥</span><span className="build-stamp"><b>Última actualización {timeSinceBuild(clock)}</b><small>Compilación (hora Costa Rica): {new Date(buildTimestamp).toLocaleString("es-CR",{dateStyle:"medium",timeStyle:"medium",timeZone:"America/Costa_Rica"})}</small></span><span>{syncLabel[syncStatus]}</span></footer></div></main>
    {flow&&<FinanceDialog label={flow==="Ingreso"?"Registrar ingreso":"Registrar gasto"} onClose={()=>setFlow(null)}><section className="flow-modal"><header><button aria-label={step?"Volver al paso anterior":"Cancelar movimiento"} onClick={()=>step?setStep(step-1):setFlow(null)}>‹</button><div><small>PASO {step+1} DE {flow==="Ingreso"?2:3}</small><h2>{flow==="Ingreso"?(step===0?"Registrar ingreso":"¿Qué quieres hacer con este dinero?"):(step===0?"Registrar gasto":step===1?"Asignar a sobres":"Productos y detalles")}</h2></div><button aria-label="Cerrar diálogo" onClick={()=>setFlow(null)}>×</button></header>
      {flowEnvelopeId&&<p className="flow-intro">Sobre: <b>{flowEnvelope?.name??"Sobre no disponible"}</b> · El monto completo se aplicará a este sobre.</p>}{formError&&<p className="form-error" role="alert">{formError}</p>}{flow==="Ingreso"&&step===0&&<div className="flow-body"><label htmlFor="finance-monto-3">Monto</label><div className="currency-input"><span>₡</span><input id="finance-monto-3" autoFocus type="number" min="0" placeholder="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></div><label htmlFor="finance-moneda-4">Moneda</label><select id="finance-moneda-4" defaultValue="CRC"><option value="CRC">Costa Rica · CRC (₡)</option></select><label htmlFor="finance-nombre-del-ingreso-5">Nombre del ingreso</label><input id="finance-nombre-del-ingreso-5" value={draft.name||(!data.customNames?suggestedName():"")} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ej. Salario semanal"/><AccountSelector accounts={data.accounts} value={draft.accountId} onChange={accountId=>setDraft(d=>({...d,accountId}))} onCreate={createAccount} display={display}/><label htmlFor="finance-fecha-y-hora-7">Fecha y hora</label><input id="finance-fecha-y-hora-7" type="datetime-local" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/><label htmlFor="finance-referencia-opcional-8">Referencia (opcional)</label><input id="finance-referencia-opcional-8" value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})} placeholder="Semana, factura…"/><label htmlFor="finance-descripci-n-opcional-9">Descripción (opcional)</label><textarea id="finance-descripci-n-opcional-9" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Añade un detalle"/><button className="primary wide" disabled={!Number.isSafeInteger(amount)||amount<=0} onClick={()=>setStep(1)}>Continuar →</button></div>}
      {flow==="Ingreso"&&step===1&&!flowEnvelopeId&&<div className="flow-body"><p className="flow-intro">Elige cómo manejar {money(amount)}.</p><button className={`choice ${!draft.unassigned?"chosen":""}`} onClick={()=>setDraft({...draft,unassigned:false})}><span>▤</span><b>Distribuir ahora<small>Asignar este ingreso a tus sobres</small></b><input type="radio" readOnly checked={!draft.unassigned}/></button><button className={`choice ${draft.unassigned?"chosen":""}`} onClick={()=>setDraft({...draft,unassigned:true,allocations:{}})}><span>▱</span><b>Dejar sin asignar<small>Guardar como dinero disponible</small></b><input type="radio" readOnly checked={draft.unassigned}/></button>{!draft.unassigned&&<div className="allocation-list">{activeEnvelopes.map(e=><label key={e.id}><span>{e.icon} {e.name}</span><div className="alloc-input">₡<input type="number" min="0" max={amount} placeholder="0" value={draft.allocations[e.id]||""} onChange={ev=>setDraft({...draft,allocations:{...draft.allocations,[e.id]:ev.target.value}})}/></div></label>)}<div className="allocation-total">Asignado <b>{money(totalAlloc)} / {money(amount)}</b></div></div>}<button className="primary wide" disabled={!amount||(!draft.unassigned&&totalAlloc>amount)} onClick={finish}>Guardar ingreso ✓</button></div>}
      {flow==="Gasto"&&step===0&&<div className="flow-body"><label htmlFor="finance-nombre-10">Nombre</label><input id="finance-nombre-10" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Se generará automáticamente"/><label htmlFor="finance-monto-total-11">Monto total</label><div className="currency-input"><span>₡</span><input id="finance-monto-total-11" autoFocus type="number" min="0" placeholder="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></div><AccountSelector accounts={data.accounts} value={draft.accountId} onChange={accountId=>setDraft(d=>({...d,accountId}))} onCreate={createAccount} display={display}/><label htmlFor="finance-fecha-y-hora-13">Fecha y hora</label><input id="finance-fecha-y-hora-13" type="datetime-local" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/><label htmlFor="finance-categor-a-14">Categoría</label><select id="finance-categor-a-14" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{["Alimentación","Transporte","Hogar","Servicios","Salud","Educación","Entretenimiento","Ropa","Mascotas","Otros"].map(c=><option key={c}>{c}</option>)}</select><label htmlFor="finance-descripci-n-opcional-15">Descripción (opcional)</label><textarea id="finance-descripci-n-opcional-15" value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="¿En qué fue el gasto?"/><button className="primary wide" disabled={!Number.isSafeInteger(amount)||amount<=0} onClick={()=>setStep(1)}>Siguiente →</button></div>}
      {flow==="Gasto"&&step===1&&!flowEnvelopeId&&<div className="flow-body"><p className="flow-intro">Distribuye el gasto entre uno o varios sobres. Total: <b>{money(amount)}</b></p>{activeEnvelopes.map(e=><label className="allocation-row" key={e.id}><span>{e.icon} {e.name}<small>Disponible {display(e.balance)}</small></span><div className="alloc-input">₡<input type="number" min="0" max={amount} placeholder="0" value={draft.allocations[e.id]||""} onChange={ev=>setDraft({...draft,allocations:{...draft.allocations,[e.id]:ev.target.value}})}/></div></label>)}<div className="allocation-total">Asignado <b>{money(totalAlloc)} / {money(amount)}</b></div><button className="secondary wide" onClick={()=>setDraft({...draft,allocations:{}})}>Usar dinero sin asignar</button><button className="primary wide" disabled={totalAlloc>amount} onClick={()=>setStep(2)}>Siguiente →</button></div>}
      {flowEnvelopeId&&step===1&&<div className="flow-body"><div className="review-box"><b>{flowEnvelope?.icon} {flowEnvelope?.name??"Sobre no disponible"}</b><span>{money(amount)} · {flow==="Ingreso"?"Se ingresará a la cuenta y se asignará a este sobre.":"Se descontará de la cuenta y de este sobre."}</span><span>Cuenta: {data.accounts.find(a=>a.id===draft.accountId)?.name}</span></div><button className="primary wide" disabled={!amount||!flowEnvelope||flowEnvelope.archived} onClick={()=>flow==="Ingreso"?finish():setStep(2)}>{flow==="Ingreso"?"Guardar ingreso ✓":"Siguiente →"}</button></div>}
      {flow==="Gasto"&&step===2&&<div className="flow-body"><PurchaseProductsEditor items={purchaseProducts} onChange={setPurchaseProducts} envelopes={activeEnvelopes.filter(e=>Number(flowAllocations[e.id])>0)} total={amount}/><label htmlFor="expense-payment-method">Método de pago (opcional)</label><select id="expense-payment-method" value={draft.paymentMethod} onChange={event=>setDraft({...draft,paymentMethod:event.target.value})}><option value="">Sin especificar</option>{paymentMethods.map(method=><option key={method}>{method}</option>)}</select><label htmlFor="expense-tags">Etiquetas (opcional)</label><input id="expense-tags" value={draft.tags} onChange={event=>setDraft({...draft,tags:event.target.value})} placeholder="Trabajo, almuerzo" aria-describedby="expense-tags-hint"/><small id="expense-tags-hint">Separadas por comas · hasta 12 etiquetas de 40 caracteres.</small><label htmlFor="finance-comercio-lugar-18">Comercio / lugar</label><input id="finance-comercio-lugar-18" value={draft.merchant} onChange={e=>setDraft({...draft,merchant:e.target.value})} placeholder="Dónde se realizó"/><label htmlFor="finance-referencia-19">Referencia</label><input id="finance-referencia-19" value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})} placeholder="Factura o nota"/><div className="review-box"><b>{draft.name||draft.category}</b><span>{money(amount)} · {draft.category}</span>{draft.description&&<span>{draft.description}</span>}{draft.merchant&&<span>{draft.merchant}</span>}<span>{totalAlloc?`${money(totalAlloc)} asignados a sobres`:"Se descontará de la cuenta y del dinero sin asignar"}</span></div><button className="primary wide" disabled={!amount||totalAlloc>amount} onClick={finish}>Guardar gasto ✓</button></div>}
    </section></FinanceDialog>}
    {showAccountForm&&<FinanceDialog label="Agregar cuenta" onClose={()=>setShowAccountForm(false)}><form className="flow-modal" noValidate onSubmit={e=>{e.preventDefault();setFormError("");const form=new FormData(e.currentTarget),name=String(form.get("name")||"").trim();if(!name){setFormError("Escribe el nombre de la cuenta.");return;}try{createAccount(name,String(form.get("type")||"Banco"));setShowAccountForm(false);setNotice("Cuenta agregada");}catch(error){setFormError(error instanceof Error?error.message:"No se pudo agregar la cuenta. Inténtalo de nuevo.");}}}><header><button type="button" aria-label="Cancelar" onClick={()=>setShowAccountForm(false)}>‹</button><div><small>CUENTAS</small><h2>Agregar cuenta</h2></div><button type="button" aria-label="Cerrar diálogo" onClick={()=>setShowAccountForm(false)}>×</button></header><div className="flow-body">{formError&&<p className="form-error" role="alert">{formError}</p>}<label htmlFor="finance-nombre-21">Nombre</label><input id="finance-nombre-21" name="name" required placeholder="Ej. Cuenta de ahorro"/><label htmlFor="finance-tipo-22">Tipo</label><select id="finance-tipo-22" name="type"><option>Banco</option><option>Efectivo</option><option>Tarjeta</option><option>Otro</option></select><p className="flow-intro">El saldo inicial es ₡0. Registra un ingreso para añadir fondos con historial.</p><button className="primary wide">Agregar cuenta</button></div></form></FinanceDialog>}
    {navigation.overlay==="repay"&&repayLoan&&<FinanceDialog label="Devolver préstamo" onClose={()=>setRepayLoan(null)}><form className="flow-modal" noValidate onSubmit={e=>{e.preventDefault();const amount=Number(new FormData(e.currentTarget).get("amount"));confirmRepayment(repayLoan,amount);}}><header><button type="button" aria-label="Cancelar" onClick={()=>setRepayLoan(null)}>‹</button><div><small>PRÉSTAMO ENTRE SOBRES</small><h2>Devolver préstamo</h2></div><button type="button" aria-label="Cerrar diálogo" onClick={()=>setRepayLoan(null)}>×</button></header><div className="flow-body"><p className="flow-intro">{repayLoan.targetName} devuelve a {repayLoan.sourceName}. Pendiente: {display(repayLoan.outstanding)} · Disponible: {display(data.envelopes.find(e=>e.id===repayLoan.targetId)?.balance||0)}</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<label htmlFor="finance-monto-a-devolver-23">Monto a devolver</label><div className="currency-input"><span>₡</span><input id="finance-monto-a-devolver-23" name="amount" required type="number" min="1" max={Math.min(repayLoan.outstanding,data.envelopes.find(e=>e.id===repayLoan.targetId)?.balance||0)} defaultValue={Math.min(repayLoan.outstanding,data.envelopes.find(e=>e.id===repayLoan.targetId)?.balance||0)}/></div><button className="primary wide" disabled={(data.envelopes.find(e=>e.id===repayLoan.targetId)?.balance||0)<=0}>Confirmar devolución</button></div></form></FinanceDialog>}    {navigation.overlay==="action"&&envelopeAction&&data.envelopes.some(e=>e.id===envelopeAction.sourceId)&&<EnvelopeActionDialog kind={envelopeAction.kind} envelope={data.envelopes.find(e=>e.id===envelopeAction.sourceId)!} others={activeEnvelopes} available={available} display={display} onSave={(amount,counterpartyId)=>{let message="";setData(d=>{const result=applyEnvelopeOperation({accounts:d.accounts,envelopes:d.envelopes,loans:d.loans,movements:d.movements},{kind:envelopeAction.kind,envelopeId:envelopeAction.sourceId,counterpartyId,amount,date:today(),id:envelopeAction.id});message=result.message;return {...d,...result.ledger,envelopes:result.ledger.envelopes as Envelope[],bank:totals(result.ledger).accounts};});setNotice(data.hidden?"Operación registrada correctamente.":message);}} onClose={navigation.close}/>}
    {showEnvelopeForm&&<EnvelopeEditor envelope={envelopeDraft} onSave={saveEnvelope} onClose={navigation.close}/>}
    {navigation.overlay==="goal"&&envelopeDraft&&<EnvelopeGoalEditor envelope={envelopeDraft} today={today().slice(0,10)} onSave={patch=>{setData(d=>({...d,envelopes:saveGoalSettings(d.envelopes,{...envelopeDraft,...patch},envelopeDraft)}));setNotice("Configuración de meta guardada.");}} onClose={envelopeDraft.returnToPlanning?navigation.back:navigation.close}/>}
    {navigation.overlay==="reset"&&<FinanceResetDialog cloud={cloudEnabled} onReset={resetFinances} onClose={navigation.back} onBackup={store.downloadBackup}/>}
    {navigation.overlay==="proximity"&&<GlobalPlanningDialog envelopes={data.envelopes} today={today().slice(0,10)} filter={(navigation.context as {filter?:ProximityFilter}|null)?.filter} onFilter={filter=>navigation.open({context:{filter}},true)} display={display} privateMode={data.hidden} onClose={navigation.back} onSelect={(envelopeId,item)=>navigation.open({overlay:"planningDetail",context:{envelopeId,itemId:item.id,kind:item.kind}})}/>}
    {navigation.overlay==="planning"&&planningEnvelope&&planningAnchor&&<EnvelopePlanningMenu envelope={planningEnvelope} today={today().slice(0,10)} anchor={planningAnchor} filter={planningContext?.filter} onAll={()=>navigation.open({context:{...planningContext,filter:undefined}},true)} display={display} privateMode={data.hidden} onClose={navigation.back} onAdd={kind=>kind==="goal"?navigation.open({overlay:"goal",context:{...planningEnvelope,returnToPlanning:true}}):openScheduled(planningEnvelope.id)} onSelect={(item,pay)=>navigation.open({overlay:"planningDetail",context:{envelopeId:planningEnvelope.id,kind:item.kind,itemId:item.id,pay}})}/>}
    {navigation.overlay==="planningDetail"&&planningEnvelope&&planningContext?.kind&&planningContext.itemId&&<EnvelopePlanningDetail backLabel={view==="Cronograma"?"Volver al cronograma":undefined} onCreateAccount={createAccount} destinations={activeEnvelopes} onMove={(targetId,moveContribution)=>{if(planningContext.kind==="goal"){const goalId=planningEnvelope.goalId||crypto.randomUUID();setData(d=>({...d,envelopes:moveEnvelopeGoal(d.envelopes,planningEnvelope,targetId,goalId,moveContribution)}));navigation.open({context:{...planningContext,envelopeId:targetId,itemId:goalId}},true);setNotice("Meta trasladada. Los saldos no cambiaron.");}else{const original=planningEnvelope.scheduledAmounts?.find(item=>item.id===planningContext.itemId);if(!original)throw new Error("El importe ya no está disponible.");setData(d=>({...d,envelopes:moveScheduledAmount(d.envelopes,planningEnvelope.id,targetId,original)}));navigation.open({context:{...planningContext,envelopeId:targetId}},true);setNotice("Importe trasladado. Los saldos y pagos anteriores no cambiaron.");}}} startPayment={planningContext.pay} envelope={planningEnvelope} itemId={planningContext.itemId} kind={planningContext.kind} today={today().slice(0,10)} display={display} privateMode={data.hidden} onBack={navigation.back} accounts={data.accounts} onPay={(amount,accountId)=>{setData(d=>{const next=payScheduledAmount({accounts:d.accounts,envelopes:d.envelopes,loans:d.loans,movements:d.movements},planningEnvelope.id,planningContext.itemId!,amount,accountId,today());return {...d,...next,envelopes:next.envelopes as Envelope[],bank:totals(next).accounts};});setNotice("Pago registrado correctamente.");}} onEdit={()=>{if(planningContext.kind==="goal")navigation.open({overlay:"goal",context:{...planningEnvelope,returnToPlanning:true}});else {const item=planningEnvelope.scheduledAmounts?.find(item=>item.id===planningContext.itemId);if(item)openScheduled(planningEnvelope.id,item);}}}/>}
    {navigation.overlay==="scheduled"&&planningEnvelope&&planningContext&&<ScheduledAmountEditor key={planningContext.original?.id||"new"} envelopeName={planningEnvelope.name} original={planningContext.original??null} today={today().slice(0,10)} onSave={item=>{setData(d=>({...d,envelopes:saveScheduledAmount(d.envelopes,planningEnvelope.id,item,planningContext.original??null)}));setNotice("Importe programado guardado. Los saldos no cambiaron.");}} onClose={navigation.back}/>}
    {navigation.overlay==="postpone"&&envelopeDraft?.recurrence&&<PostponeEditor envelope={{name:envelopeDraft.name,recurrence:envelopeDraft.recurrence}} today={today().slice(0,10)} onSave={option=>{setData(d=>{const next=postponeRecurringContribution({accounts:d.accounts,envelopes:d.envelopes,loans:d.loans,movements:d.movements},envelopeDraft.id,envelopeDraft.recurrence!.nextDate,today().slice(0,10),option);return {...d,...next,envelopes:next.envelopes as Envelope[]};});setNotice("Aporte pospuesto.");}} onClose={navigation.close}/>}
    {navigation.overlay==="new"&&<FinanceDialog label="Nuevo movimiento" onClose={navigation.close}><section className="flow-modal"><header><h2>Nuevo movimiento</h2><button aria-label="Cerrar diálogo" onClick={navigation.close}>×</button></header><div className="flow-body">{(navigation.context as {envelopeId?:string}|null)?.envelopeId&&<p className="flow-intro">Sobre: {data.envelopes.find(e=>e.id===(navigation.context as {envelopeId:string}).envelopeId)?.name}</p>}<button className="choice" onClick={()=>openFlow("Ingreso",(navigation.context as {envelopeId?:string}|null)?.envelopeId)}>＋ Entrada · Registrar ingreso</button><button className="choice" onClick={()=>openFlow("Gasto",(navigation.context as {envelopeId?:string}|null)?.envelopeId)}>− Salida · Registrar gasto</button></div></section></FinanceDialog>}
    {envelopeMenu&&menuEnvelope&&<EnvelopeContextMenu anchor={envelopeMenu.anchor} name={menuEnvelope.name} onClose={()=>setEnvelopeMenu(null)} actions={[
      {label:"Asignar dinero",onSelect:()=>setEnvelopeAction({kind:"Asignar dinero",sourceId:menuEnvelope.id})},
      {label:"Desasignar",onSelect:()=>setEnvelopeAction({kind:"Desasignar",sourceId:menuEnvelope.id})},
      {label:"Transferir",onSelect:()=>setEnvelopeAction({kind:"Transferir",sourceId:menuEnvelope.id})},
      {label:"Prestar a otro sobre",onSelect:()=>setEnvelopeAction({kind:"Prestar a otro sobre",sourceId:menuEnvelope.id})},
      {label:"Pedir prestado",onSelect:()=>setEnvelopeAction({kind:"Pedir prestado",sourceId:menuEnvelope.id})},
      {label:"Productos",onSelect:()=>navigation.open({overlay:"products",context:{envelopeId:menuEnvelope.id}})},
      {label:"Configurar meta",onSelect:()=>openGoal(menuEnvelope)},
      {label:"Programar importe a este sobre",onSelect:()=>openScheduled(menuEnvelope.id)},
      {label:"Metas e importes",onSelect:()=>openPlanning(menuEnvelope.id,envelopeMenu.anchor)},
      {label:menuEnvelope.balanceHidden?"Mostrar saldo del sobre":"Ocultar saldo del sobre",onSelect:()=>setData(d=>({...d,envelopes:d.envelopes.map(e=>e.id===menuEnvelope.id?{...e,balanceHidden:!e.balanceHidden}:e)}))},
      {label:"Editar sobre",onSelect:()=>openEditor(menuEnvelope)},
      {label:"Ver movimientos",onSelect:()=>showEnvelopeMovements(menuEnvelope)},
      {label:"Archivar",danger:true,onSelect:()=>archiveEnvelope(menuEnvelope)},
    ]}/>}
    {navigation.overlay==="products"&&data.envelopes.some(e=>e.id===(navigation.context as {envelopeId:string})?.envelopeId)&&<EnvelopeProductsDialog envelope={data.envelopes.find(e=>e.id===(navigation.context as {envelopeId:string}).envelopeId)!} movements={data.movements} today={today().slice(0,10)} display={display} onSave={product=>setData(d=>({...d,envelopes:saveTrackedProduct(d.envelopes,(navigation.context as {envelopeId:string}).envelopeId,product)}))} onClose={navigation.back} onMovement={movementId=>{setSearch("");setFilter("Todos");navigation.open({view:"Movimientos",overlay:null,context:null,movementId,movementEnvelopeId:null,historyFrom:"",historyTo:""});}}/>}
    {navigation.overlay==="incomeTrace"&&<IncomeTraceDialog ledger={ledger} movementId={(navigation.context as {movementId:string}).movementId} display={display} hidden={data.hidden} onBack={navigation.back} onIncome={id=>navigation.open({overlay:"incomeTrace",context:{movementId:id}})} onEnvelope={id=>{setSearch("");setFilter("Todos");navigation.open({view:"Movimientos",overlay:null,movementEnvelopeId:id,movementId:null});}}/>}
    {navigation.overlay==="feedback"&&<FeedbackDialog onClose={navigation.close}/>}
    {summaryMenu&&<EnvelopeContextMenu anchor={summaryMenu.anchor} name={summaryMenu.label} onClose={()=>setSummaryMenu(null)} actions={[{label:data.summaryPrivacy[summaryMenu.key]?"Mostrar monto":"Ocultar monto",onSelect:()=>setData(d=>({...d,summaryPrivacy:{...d.summaryPrivacy,[summaryMenu.key]:!d.summaryPrivacy[summaryMenu.key]}}))}]}/>}
    {notice&&<div className="toast" role="status">{notice}<button aria-label="Cerrar aviso" onClick={()=>setNotice("")}>×</button></div>}
  </div>;
}
function Summary({icon,label,value,foot,accent=false,onPrivacy}:{icon?:string;label:string;value:string;foot:string;accent?:boolean;onPrivacy?:(event:React.MouseEvent<HTMLButtonElement>)=>void}){const heading=<><span>{label}</span><i>{icon||"₡"}</i></>;return <div className={`summary-card ${accent?"accent":""}`}>{onPrivacy?<button className="summary-top summary-privacy" aria-label={`Privacidad de ${label}`} title={`Ocultar o mostrar ${label}`} aria-haspopup="menu" onClick={onPrivacy}>{heading}</button>:<div className="summary-top">{heading}</div>}<b className="summary-value">{value}</b><small>{foot}</small></div>}

function MovementList({items,hidden,onTrace}:{items:Movement[];hidden:boolean;onTrace:(id:string)=>void}){return items.length?<div className="movement-list">{items.map(m=><div className="movement-row" key={m.id}><span className={`movement-icon ${m.type==="Ingreso"?"ingreso":m.type==="Gasto"?"gasto":"transferencia"}`}>{m.type==="Ingreso"?"＋":m.type==="Gasto"?"−":"⇄"}</span><span className="movement-copy"><b>{hidden?m.type:m.name}</b><small>{[m.accountName,m.category,(m.type==="Ingreso"||m.type==="Gasto")?m.allocations.map(a=>a.name).join(" · "):undefined,hidden?undefined:m.description,hidden?undefined:m.merchant,hidden?undefined:m.paymentMethod,...(hidden?[]:(m.tags??[]).map(tag=>`#${tag}`)),hidden||m.reference===m.scheduledAmountId?undefined:m.reference,new Date(/(?:Z|[+-]\d{2}:\d{2})$/.test(m.date)?m.date:`${m.date}-06:00`).toLocaleString("es-CR",{dateStyle:"short",timeStyle:"short",timeZone:"America/Costa_Rica"})].filter(Boolean).join(" · ")}</small>{!hidden&&Boolean(m.products?.length)&&<details><summary>Productos ({m.products!.length})</summary>{m.products!.map((p,index)=><p key={index}>{p.name} · {money(p.amount)}{p.quantity?` · Cantidad: ${p.quantity}`:""}{p.notes?` · ${p.notes}`:""}</p>)}</details>}{(m.type==="Ingreso"||m.type==="Asignación")&&<button className="text-btn trace-link" onClick={()=>onTrace(m.id)}>{m.type==="Ingreso"?"Ver distribución del ingreso":"Ver ingreso de origen"}</button>}</span><strong className={m.type==="Ingreso"?"positive":m.type==="Gasto"?"negative":""}>{m.type==="Ingreso"?"+":m.type==="Gasto"?"−":"↔ "}{hidden?"••••":money(m.amount)}</strong></div>)}</div>:<div className="empty-state"><span>◷</span><b>Aún no hay movimientos</b><small>Cuando registres ingresos o gastos, aparecerán aquí.</small></div>}
