"use client";

import { useEffect, useMemo, useState } from "react";
import { useThemeMode } from "@/components/theme-provider";
import { createClient as createSupabaseClient, isSupabaseConfigured } from "@/lib/supabase/client";

type Envelope = { id: string; name: string; icon: string; balance: number; color: string };
type Movement = { id: string; type: "Ingreso" | "Gasto" | "Transferencia"; name: string; amount: number; date: string; category: string; allocations: { name: string; amount: number }[]; products?: { name: string; amount: number }[] };
type Data = { envelopes: Envelope[]; bank: number; movements: Movement[]; hidden: boolean; fields: string[]; customNames: boolean };
const initial: Data = { envelopes: [{ id:"home",name:"Hogar",icon:"🏠",balance:0,color:"peach" },{ id:"food",name:"Alimentación",icon:"🛒",balance:0,color:"green" },{ id:"transport",name:"Transporte",icon:"🚙",balance:0,color:"blue" },{ id:"savings",name:"Ahorro",icon:"🐷",balance:0,color:"amber" },{ id:"emergency",name:"Emergencia",icon:"🛡️",balance:0,color:"lilac" }], bank:0, movements:[], hidden:false, fields:["Fecha","Monto"], customNames:false };
const money = (n:number) => `₡${Math.round(n).toLocaleString("es-CR")}`;
const today = () => new Date().toISOString().slice(0,16);

export default function HomePage() {
  const [data,setData]=useState<Data>(initial), [ready,setReady]=useState(false), [view,setView]=useState("Inicio"), [flow,setFlow]=useState<"Ingreso"|"Gasto"|null>(null), [step,setStep]=useState(0), [draft,setDraft]=useState({name:"",amount:"",date:today(),reference:"",description:"",category:"Alimentación",allocations:{} as Record<string,string>,products:"",productAmount:"",unassigned:false});
  const [filter,setFilter]=useState("Todos"), [search,setSearch]=useState(""), [notice,setNotice]=useState(""); const {mode,toggleMode}=useThemeMode();
  const cloudEnabled=isSupabaseConfigured();
  const supabase=useMemo(()=>cloudEnabled?createSupabaseClient():null,[cloudEnabled]);
  const [authUser,setAuthUser]=useState<{id:string;email?:string} | null>(null),[authLoading,setAuthLoading]=useState(cloudEnabled),[authBusy,setAuthBusy]=useState(false),[authEmail,setAuthEmail]=useState(""),[authPassword,setAuthPassword]=useState(""),[authError,setAuthError]=useState(""),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[cloudReady,setCloudReady]=useState(false);
  useEffect(()=>{try{const raw=localStorage.getItem("claro-finanzas-v2");if(raw)setData({...initial,...JSON.parse(raw)});}catch{}setReady(true);},[]);
  useEffect(()=>{if(ready)localStorage.setItem("claro-finanzas-v2",JSON.stringify(data));},[data,ready]);
  useEffect(()=>{
    if(!supabase){setAuthLoading(false);return;}
    let alive=true;
    const load=async(userId:string)=>{
      setCloudReady(false);
      const {data:row,error}=await supabase.from("user_finance_data").select("data").eq("user_id",userId).maybeSingle();
      if(!alive)return;
      if(error){setAuthError(`No se pudieron cargar tus datos: ${error.message}`);setCloudReady(true);return;}
      if(row?.data)setData({...initial,...row.data as Partial<Data>});
      else {
        let cached:Data=initial;
        try{const raw=localStorage.getItem("claro-finanzas-v2");if(raw)cached={...initial,...JSON.parse(raw)};}catch{}
        setData(cached);
        const {error:saveError}=await supabase.from("user_finance_data").upsert({user_id:userId,data:cached,updated_at:new Date().toISOString()});
        if(saveError&&alive)setAuthError(`No se pudieron guardar los datos iniciales: ${saveError.message}`);
      }
      if(alive)setCloudReady(true);
    };
    supabase.auth.getUser().then(({data:{user}})=>{if(!alive)return;setAuthUser(user?{id:user.id,email:user.email}:null);setAuthLoading(false);if(user)void load(user.id);});
    const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{
      if(!alive)return;
      const user=session?.user;
      setAuthUser(user?{id:user.id,email:user.email}:null);
      setAuthLoading(false);
      if(user)void load(user.id);else setCloudReady(false);
    });
    return()=>{alive=false;subscription.unsubscribe();};
  },[supabase]);
  useEffect(()=>{
    if(!supabase||!authUser||!cloudReady)return;
    const timer=window.setTimeout(async()=>{
      const {error}=await supabase.from("user_finance_data").upsert({user_id:authUser.id,data,updated_at:new Date().toISOString()});
      if(error)setNotice(`Error al sincronizar: ${error.message}`);
    },450);
    return()=>window.clearTimeout(timer);
  },[data,supabase,authUser,cloudReady]);
  const submitAuth=async(e:React.FormEvent<HTMLFormElement>)=>{
    e.preventDefault();if(!supabase)return;setAuthBusy(true);setAuthError("");
    const result=authMode==="login"?await supabase.auth.signInWithPassword({email:authEmail,password:authPassword}):await supabase.auth.signUp({email:authEmail,password:authPassword});
    if(result.error)setAuthError(result.error.message);
    else if(authMode==="signup"&&!result.data.session)setAuthError("Cuenta creada. Revisa tu correo para confirmar y luego inicia sesión.");
    setAuthBusy(false);
  };
  const assigned=data.envelopes.reduce((s,e)=>s+e.balance,0), available=data.bank-assigned;
  const display=(n:number)=>data.hidden?"••••••":money(n);
  const openFlow=(type:"Ingreso"|"Gasto")=>{setFlow(type);setStep(0);setDraft({name:"",amount:"",date:today(),reference:"",description:"",category:"Alimentación",allocations:{},products:"",productAmount:"",unassigned:false});};
  const totalAlloc=Object.values(draft.allocations).reduce((s,n)=>s+(Number(n)||0),0), amount=Number(draft.amount)||0;
  const suggestedName=()=>{const parts:Record<string,string>={Fecha:new Date(draft.date).toLocaleDateString("es-CR"),Hora:new Date(draft.date).toLocaleTimeString("es-CR",{hour:"2-digit",minute:"2-digit"}),Monto:money(amount),Categoría:draft.category,"Tipo de ingreso":draft.category,Semana:`Semana ${Math.ceil(new Date(draft.date).getDate()/7)}`,Número:`#${String(data.movements.filter(m=>m.type===flow).length+1).padStart(3,"0")}`};return data.fields.map(k=>parts[k]).filter(Boolean).join(" - ")||money(amount);};
  const finish=()=>{const name=draft.name.trim()||suggestedName(); const allocations=Object.entries(draft.allocations).filter(([,v])=>Number(v)>0).map(([id,v])=>({name:data.envelopes.find(e=>e.id===id)?.name||"Sobre",amount:Number(v)})); const products=draft.products.trim()?[{name:draft.products.trim(),amount:Number(draft.productAmount)||0}]:[];
    if(flow==="Ingreso") {const dist=draft.unassigned?[]:allocations;setData(d=>({...d,bank:d.bank+amount,envelopes:d.envelopes.map(e=>({...e,balance:e.balance+(dist.find(a=>a.name===e.name)?.amount||0)})),movements:[{id:crypto.randomUUID(),type:"Ingreso",name,amount,date:draft.date,category:"Ingreso",allocations:dist},...d.movements]}));}
    else {const dist=allocations.length?allocations:[{name:"Banco",amount}];setData(d=>({...d,bank:d.bank-amount,envelopes:d.envelopes.map(e=>({...e,balance:e.balance-(dist.find(a=>a.name===e.name)?.amount||0)})),movements:[{id:crypto.randomUUID(),type:"Gasto",name,amount,date:draft.date,category:draft.category,allocations:dist,products},...d.movements]}));}
    setFlow(null);setNotice(`${flow} registrado`);setTimeout(()=>setNotice(""),2400);
  };
  const filtered=useMemo(()=>data.movements.filter(m=>(filter==="Todos"||m.type===filter)&&(`${m.name} ${m.category} ${m.allocations.map(a=>a.name).join(" ")}`).toLowerCase().includes(search.toLowerCase())),[data.movements,filter,search]);
  const toggleField=(field:string)=>setData(d=>({...d,fields:d.fields.includes(field)?d.fields.filter(f=>f!==field):[...d.fields,field]}));

  if(cloudEnabled&&(authLoading||(authUser&&!cloudReady)))return <div className="auth-screen"><section className="auth-card"><div className="logo"><span>c</span> claro</div><div className="auth-spinner"/><h1>{authLoading?"Conectando con tu cuenta":"Cargando tus datos"}</h1><p>Un momento, estamos preparando tu espacio financiero.</p></section></div>;
  if(cloudEnabled&&!authUser)return <div className="auth-screen"><form className="auth-card" onSubmit={submitAuth}><div className="logo"><span>c</span> claro</div><div className="overline">TUS FINANZAS, A TU MANERA</div><h1>{authMode==="login"?"Bienvenido de nuevo":"Crea tu cuenta"}</h1><p>{authMode==="login"?"Inicia sesión para sincronizar tus sobres y movimientos.":"Tus datos se guardarán de forma privada en tu cuenta."}</p><label>Correo electrónico</label><input type="email" autoComplete="email" required value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="tu@correo.com"/><label>Contraseña</label><input type="password" minLength={6} autoComplete={authMode==="login"?"current-password":"new-password"} required value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder="Al menos 6 caracteres"/>{authError&&<div className="auth-error">{authError}</div>}<button className="primary wide" disabled={authBusy}>{authBusy?"Un momento…":authMode==="login"?"Iniciar sesión":"Crear cuenta"}</button><button type="button" className="auth-switch" onClick={()=>{setAuthMode(authMode==="login"?"signup":"login");setAuthError("")}}>{authMode==="login"?"¿Primera vez? Crea una cuenta":"Ya tienes cuenta? Inicia sesión"}</button></form></div>;

  return <div className={`finance-app ${mode==="dark"?"dark-mode":""}`}>
    <aside className="side-nav"><a className="logo" onClick={()=>setView("Inicio")}><span>c</span> claro</a><div className="side-caption">TU DINERO</div>{["Inicio","Movimientos","Sobres","Reportes","Configuración"].map((v,i)=><button key={v} className={`nav-item ${view===v?"selected":""}`} onClick={()=>setView(v)}><span>{["⌂","⇄","▣","▥","⚙"][i]}</span>{v}</button>)}<div className="side-bottom"><div className="side-tip">✦ <strong>Un paso a la vez.</strong><br/>Tu dinero, con intención.</div><div className="user-chip"><span>M</span><div><b>{authUser?.email||"Mi espacio"}</b><small>{cloudEnabled?"Sincronizado con Supabase":"Solo este navegador"}</small></div>{authUser&&<button className="logout" onClick={()=>void supabase?.auth.signOut()}>Salir</button>}</div></div></aside>
    <main className="workspace"><header className="app-header"><div className="crumb">Mi espacio <span>/</span> <b>{view}</b></div><div className="header-tools"><span>{new Date().toLocaleDateString("es-CR",{weekday:"long",day:"numeric",month:"long"})}</span><button aria-label="Alternar tema" onClick={toggleMode}>◐</button><button aria-label="Privacidad" onClick={()=>setData(d=>({...d,hidden:!d.hidden}))}>{data.hidden?"◉":"◎"}</button><button className="avatar">M</button></div></header>
    <div className="page-content"><div className="page-title"><div><div className="overline">✦ TU DINERO, CON INTENCIÓN</div><h1>{view==="Inicio"?"Mis Sobres":view}</h1><p>{view==="Inicio"?"Cada peso tiene un lugar. Aquí puedes ver el tuyo.":view==="Movimientos"?"Todo lo que entra y sale, en un solo lugar.":view==="Sobres"?"Organiza tu dinero para lo que más importa.":view==="Reportes"?"Una mirada sencilla a tu dinero este mes.":"Haz que la app funcione a tu manera."}</p></div><button className="primary" onClick={()=>openFlow("Ingreso")}>＋ <span>Nuevo movimiento</span></button></div>
    {view==="Inicio"&&<>
      <div className="summary-row"><Summary icon="▣" label="Fondos actuales" value={display(data.bank)} foot="En tus cuentas"/><Summary icon="◈" label="Comprometido" value={display(assigned)} foot="Asignado a tus sobres"/><Summary icon="✳" label="Disponible" value={display(available)} foot="Listo para asignar" accent/></div>
      <section className="section"><div className="section-heading"><div><h2>Mis sobres <span className="counter">{data.envelopes.length}</span></h2><p>El saldo de cada propósito, siempre al día.</p></div><button className="text-btn" onClick={()=>setView("Sobres")}>Ver todos →</button></div><div className="envelope-list">{data.envelopes.map(e=><button className="envelope-row" key={e.id} onClick={()=>{setView("Sobres");}}><span className={`emoji ${e.color}`}>{e.icon}</span><span className="envelope-name">{e.name}<small>Disponible</small></span><b>{display(e.balance)}</b><span className="chevron">›</span></button>)}</div><button className="add-envelope" onClick={()=>setNotice("La creación de sobres estará disponible próximamente.")}>＋ Crear un sobre</button></section>
      <div className="quick-actions"><div><small>NUEVO MOVIMIENTO</small><h3>¿Qué quieres registrar?</h3></div><button onClick={()=>openFlow("Ingreso")}><i>＋</i><b>Entrada</b><small>Registrar ingreso</small></button><button onClick={()=>openFlow("Gasto")}><i className="minus">−</i><b>Salida</b><small>Registrar gasto</small></button></div>
      <section className="section recent"><div className="section-heading"><div><h2>Actividad reciente</h2><p>Los movimientos más recientes.</p></div><button className="text-btn" onClick={()=>setView("Movimientos")}>Ver historial →</button></div><MovementList items={data.movements.slice(0,4)} hidden={data.hidden}/></section>
    </>}
    {view==="Movimientos"&&<section className="section page-panel"><div className="toolbar"><input className="search" placeholder="⌕  Buscar por nombre o sobre…" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Ingreso</option><option>Gasto</option></select></div><MovementList items={filtered} hidden={data.hidden}/></section>}
    {view==="Sobres"&&<section className="section page-panel"><div className="money-banner"><span>Dinero disponible en sobres</span><b>{display(assigned)}</b></div><div className="envelope-list">{data.envelopes.map(e=><div className="envelope-row static" key={e.id}><span className={`emoji ${e.color}`}>{e.icon}</span><span className="envelope-name">{e.name}<small>Saldo actual</small></span><b>{display(e.balance)}</b></div>)}</div></section>}
    {view==="Reportes"&&<section className="section page-panel"><div className="report-cards"><Summary label="Ingresos" value={display(data.movements.filter(m=>m.type==="Ingreso").reduce((s,m)=>s+m.amount,0))} foot="Total registrado"/><Summary label="Gastos" value={display(data.movements.filter(m=>m.type==="Gasto").reduce((s,m)=>s+m.amount,0))} foot="Total registrado"/><Summary label="Ahorro en sobres" value={display(data.envelopes.find(e=>e.name==="Ahorro")?.balance||0)} foot="Saldo actual" accent/></div><h2 className="subhead">Gasto por categoría</h2>{[...new Set(data.movements.filter(m=>m.type==="Gasto").map(m=>m.category))].map(c=><div className="category-line" key={c}><span>{c}</span><b>{display(data.movements.filter(m=>m.type==="Gasto"&&m.category===c).reduce((s,m)=>s+m.amount,0))}</b></div>)}</section>}
    {view==="Configuración"&&<section className="section page-panel settings"><h2>Preferencias</h2><div className="setting-row"><div><b>Vista privada</b><small>Oculta los montos en la pantalla.</small></div><button className={`switch ${data.hidden?"on":""}`} onClick={()=>setData(d=>({...d,hidden:!d.hidden}))}>{data.hidden?"Sí":"No"}</button></div><div className="setting-row"><div><b>Nombre automático de ingresos</b><small>Elige qué datos forman el nombre sugerido.</small></div><button className={`switch ${!data.customNames?"on":""}`} onClick={()=>setData(d=>({...d,customNames:!d.customNames}))}>{data.customNames?"Manual":"Auto"}</button></div><div className="field-options">{["Fecha","Hora","Monto","Tipo de ingreso","Categoría","Semana","Número"].map(f=><label key={f}><input type="checkbox" checked={data.fields.includes(f)} onChange={()=>toggleField(f)}/>{f}<span>⠿</span></label>)}</div><div className="setting-row"><div><b>Nombre de gastos</b><small>También puedes escribir nombres al registrar un gasto.</small></div></div><button className="danger-link" onClick={()=>{if(confirm("¿Borrar los movimientos y saldos guardados en este navegador?")){setData(initial);setNotice("Datos reiniciados.");}}}>Reiniciar datos locales</button></section>}
    <footer className="footer"><span>Con calma, un día a la vez ♥</span><span>Los datos se guardan en este navegador.</span></footer></div></main>
    {flow&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setFlow(null)}}><section className="flow-modal"><header><button onClick={()=>step?setStep(step-1):setFlow(null)}>‹</button><div><small>PASO {step+1} DE {flow==="Ingreso"?2:3}</small><h2>{flow==="Ingreso"?(step===0?"Registrar ingreso":"¿Qué quieres hacer con este dinero?"):(step===0?"Registrar gasto":step===1?"Asignar a sobres":"Productos y detalles")}</h2></div><button onClick={()=>setFlow(null)}>×</button></header>
      {flow==="Ingreso"&&step===0&&<div className="flow-body"><label>Monto</label><div className="currency-input"><span>₡</span><input autoFocus type="number" min="0" placeholder="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></div><label>Moneda</label><select defaultValue="CRC"><option value="CRC">Costa Rica · CRC (₡)</option><option value="USD">Dólar · USD ($)</option></select><label>Nombre del ingreso</label><input value={draft.name||(!data.customNames?suggestedName():"")} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ej. Salario semanal"/><label>Fecha y hora</label><input type="datetime-local" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/><label>Referencia (opcional)</label><input value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})} placeholder="Semana, factura…"/><label>Descripción (opcional)</label><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Añade un detalle"/><button className="primary wide" disabled={!amount} onClick={()=>setStep(1)}>Continuar →</button></div>}
      {flow==="Ingreso"&&step===1&&<div className="flow-body"><p className="flow-intro">Elige cómo manejar {money(amount)}.</p><button className={`choice ${!draft.unassigned?"chosen":""}`} onClick={()=>setDraft({...draft,unassigned:false})}><span>▤</span><b>Distribuir ahora<small>Asignar este ingreso a tus sobres</small></b><input type="radio" readOnly checked={!draft.unassigned}/></button><button className={`choice ${draft.unassigned?"chosen":""}`} onClick={()=>setDraft({...draft,unassigned:true,allocations:{}})}><span>▱</span><b>Dejar sin asignar<small>Guardar como dinero disponible</small></b><input type="radio" readOnly checked={draft.unassigned}/></button>{!draft.unassigned&&<div className="allocation-list">{data.envelopes.map(e=><label key={e.id}><span>{e.icon} {e.name}</span><div className="alloc-input">₡<input type="number" min="0" max={amount} placeholder="0" value={draft.allocations[e.id]||""} onChange={ev=>setDraft({...draft,allocations:{...draft.allocations,[e.id]:ev.target.value}})}/></div></label>)}<div className="allocation-total">Asignado <b>{money(totalAlloc)} / {money(amount)}</b></div></div>}<button className="primary wide" disabled={!amount||(!draft.unassigned&&totalAlloc>amount)} onClick={finish}>Guardar ingreso ✓</button></div>}
      {flow==="Gasto"&&step===0&&<div className="flow-body"><label>Nombre</label><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Se generará automáticamente"/><label>Monto total</label><div className="currency-input"><span>₡</span><input autoFocus type="number" min="0" placeholder="0" value={draft.amount} onChange={e=>setDraft({...draft,amount:e.target.value})}/></div><label>Fecha y hora</label><input type="datetime-local" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/><label>Categoría</label><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{["Alimentación","Transporte","Hogar","Servicios","Salud","Educación","Entretenimiento","Ropa","Mascotas","Otros"].map(c=><option key={c}>{c}</option>)}</select><label>Descripción (opcional)</label><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="¿En qué fue el gasto?"/><button className="primary wide" disabled={!amount} onClick={()=>setStep(1)}>Siguiente →</button></div>}
      {flow==="Gasto"&&step===1&&<div className="flow-body"><p className="flow-intro">Distribuye el gasto entre uno o varios sobres. Total: <b>{money(amount)}</b></p>{data.envelopes.map(e=><label className="allocation-row" key={e.id}><span>{e.icon} {e.name}<small>Disponible {display(e.balance)}</small></span><div className="alloc-input">₡<input type="number" min="0" max={amount} placeholder="0" value={draft.allocations[e.id]||""} onChange={ev=>setDraft({...draft,allocations:{...draft.allocations,[e.id]:ev.target.value}})}/></div></label>)}<div className="allocation-total">Asignado <b>{money(totalAlloc)} / {money(amount)}</b></div><button className="secondary wide" onClick={()=>setDraft({...draft,allocations:{}})}>Dejar solo en el banco</button><button className="primary wide" disabled={totalAlloc>amount} onClick={()=>setStep(2)}>Siguiente →</button></div>}
      {flow==="Gasto"&&step===2&&<div className="flow-body"><label>Producto (opcional)</label><input value={draft.products} onChange={e=>setDraft({...draft,products:e.target.value})} placeholder="Ej. Café, supermercado…"/><label>Monto del producto (opcional)</label><div className="currency-input"><span>₡</span><input type="number" min="0" value={draft.productAmount} onChange={e=>setDraft({...draft,productAmount:e.target.value})}/></div><label>Comercio / lugar</label><input placeholder="Dónde se realizó"/><label>Referencia</label><input value={draft.reference} onChange={e=>setDraft({...draft,reference:e.target.value})} placeholder="Factura o nota"/><label>Descripción</label><textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Detalle adicional"/><div className="review-box"><b>{draft.name||draft.category}</b><span>{money(amount)} · {draft.category}</span><span>{totalAlloc?`${money(totalAlloc)} asignados a sobres`:"Se descontará del banco"}</span></div><button className="primary wide" disabled={!amount||totalAlloc>amount} onClick={finish}>Guardar gasto ✓</button></div>}
    </section></div>}
    {notice&&<div className="toast">✓ {notice}</div>}
  </div>;
}
function Summary({icon,label,value,foot,accent=false}:{icon?:string;label:string;value:string;foot:string;accent?:boolean}){return <div className={`summary-card ${accent?"accent":""}`}><div className="summary-top"><span>{label}</span><i>{icon||"₡"}</i></div><b className="summary-value">{value}</b><small>{foot}</small></div>}
function MovementList({items,hidden}:{items:Movement[];hidden:boolean}){return items.length?<div className="movement-list">{items.map(m=><div className="movement-row" key={m.id}><span className={`movement-icon ${m.type.toLowerCase()}`}>{m.type==="Ingreso"?"＋":m.type==="Gasto"?"−":"⇄"}</span><span className="movement-copy"><b>{m.name}</b><small>{m.category} · {new Date(m.date).toLocaleDateString("es-CR")}</small></span><strong className={m.type==="Ingreso"?"positive":"negative"}>{m.type==="Ingreso"?"+":"−"}{hidden?"••••":money(m.amount)}</strong></div>)}</div>:<div className="empty-state"><span>◷</span><b>Aún no hay movimientos</b><small>Cuando registres ingresos o gastos, aparecerán aquí.</small></div>}
